/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bossini._usjt_psc_segunda_sistema_academico;

import br.com.bossini._usjt_psc_segunda_sistema_academico.DAO.CursoDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.Arrays;

/**
 *
 * @author rodri
 */
public class CursosTela extends javax.swing.JFrame {
    
    

    /**
     * Creates new form CursosTela
     */
    public CursosTela() {
        super("Cursos");
        initComponents();
        buscarCursos();
        setLocationRelativeTo(null);
    }

    private void buscarCursos(){
        CursoDAO cursoDAO = new CursoDAO();
        //cláusula catch or declare
        try{
            List <Curso> cursos = cursoDAO.obterCursos();
            cursosComboBox.setModel(new DefaultComboBoxModel<>(cursos.toArray(Curso[]::new)));
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Cursos indisponíveis. Tente novamente mais tarde");
            this.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cursosComboBox = new javax.swing.JComboBox<>();
        nomeCursoTextField = new javax.swing.JTextField();
        tipoCursoTextField = new javax.swing.JTextField();
        idCursoTextField = new javax.swing.JTextField();
        novoCursoButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento de cursos"));

        nomeCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("nome"));

        tipoCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("tipo"));
        tipoCursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCursoTextFieldActionPerformed(evt);
            }
        });

        idCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("id"));

        novoCursoButton.setText("Novo");
        novoCursoButton.setToolTipText("");
        novoCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCursoButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.setEnabled(false);

        jButton3.setText("Excluir");
        jButton3.setEnabled(false);

        jButton4.setText("Cancelar");
        jButton4.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cursosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeCursoTextField)
                    .addComponent(tipoCursoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(idCursoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(novoCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(idCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCursoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novoCursoButton)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoCursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCursoTextFieldActionPerformed

    private void novoCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCursoButtonActionPerformed
       //1. Pegar tudo o que o usuário digitou (ou seja, nome e tipo do curso)
       String nomeCurso = nomeCursoTextField.getText();
       String tipoCurso = tipoCursoTextField.getText();
       //2. Verificar se ele de fato digitou os dois valores
       //3. Se o usuário tiver deixado de digitar um dos dois valores, mostrar uma mensagem de erro
       if (nomeCurso == null || nomeCurso.length() <= 0 || tipoCurso == null || tipoCurso.length() <= 0){
           JOptionPane.showMessageDialog(null, "Você deve digitar nome e tipo do curso");
       }
       else{
           try{
                //4. Senão
                //5. Construir um objeto curso
                Curso curso = new Curso(nomeCurso, tipoCurso);
                //6. Construir um objeto CursoDAO
                CursoDAO cursoDAO = new CursoDAO();
                //7. Chamar o método inserirCurso do CursoDAO
                cursoDAO.inserirCurso(curso);
                //8. Exibir uma mensagem de feedback para o usuário (cadastro feito com sucesso)
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
                //9. Limpar os campos em que o usuário digitou
                nomeCursoTextField.setText("");
                tipoCursoTextField.setText("");
                //10. Atualizar o combobox para que ele mostre o novo curso, chamando o método buscarCursos
                buscarCursos();
           }
           catch (Exception e){
               JOptionPane.showMessageDialog (null, "Cadastro do curso falhou. Tente novamente mais tarde.");
               //mostrar o log, inclui uma mensagem que explica o que causou a exceção
               e.printStackTrace();
           }
           
       
       }
       
       
    }//GEN-LAST:event_novoCursoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Curso> cursosComboBox;
    private javax.swing.JTextField idCursoTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCursoTextField;
    private javax.swing.JButton novoCursoButton;
    private javax.swing.JTextField tipoCursoTextField;
    // End of variables declaration//GEN-END:variables
}
